using Xenoh.Domain.Entities;
using Xenoh.Domain.Enums;

namespace Xenoh.Infrastructure.Persistence.Seeders;

public static class ExerciseTemplateSeeder
{
    public static List<ExerciseTemplate> GetTemplates() =>
    [
        // ── CHEST ──────────────────────────────────────────────────────────────
        new() { Name = "Bench Press",              Description = "Barbell flat bench press",                   PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Triceps, MuscleGroup.Shoulders],          IsCompetitionLift = true,  CompetitionLiftType = CompetitionLiftType.Bench,    ImageUrl = "/exercises-image/chest/benchpress.png" },
        new() { Name = "Incline Bench Press",      Description = "Barbell incline bench press",                PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Shoulders, MuscleGroup.Triceps],                                                                                              ImageUrl = "/exercises-image/chest/inclinebenchpress.png" },
        new() { Name = "Decline Bench Press",      Description = "Barbell decline bench press",               PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Triceps],                                                                                                                    ImageUrl = "/exercises-image/chest/declinebenchpress.png" },
        new() { Name = "Dumbbell Bench Press",     Description = "Flat dumbbell bench press",                  PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Triceps, MuscleGroup.Shoulders],                                                                                            ImageUrl = "/exercises-image/chest/dumbbellbenchpress.png" },
        new() { Name = "Incline Dumbbell Press",   Description = "Incline dumbbell bench press",               PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Shoulders, MuscleGroup.Triceps],                                                                                            ImageUrl = "/exercises-image/chest/inclinedumbbellbenchpress.png" },
        new() { Name = "Dumbbell Fly",             Description = "Dumbbell chest fly on flat bench",           PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Shoulders],                                                                                                                  ImageUrl = "/exercises-image/chest/dumbbellfly.png" },
        new() { Name = "Cable Crossover",          Description = "Cable chest fly crossover",                  PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Shoulders],                                                                                                                  ImageUrl = "/exercises-image/chest/cablecrossover.png" },
        new() { Name = "Chest Dip",                Description = "Parallel bar dip leaning forward",          PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Triceps, MuscleGroup.Shoulders],                                                                                            ImageUrl = "/exercises-image/chest/chestdip.png" },
        new() { Name = "Pec Deck",                 Description = "Machine pec deck / chest fly",               PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/chest/pecdeck.png" },
        new() { Name = "Push-Up",                  Description = "Bodyweight push-up",                         PrimaryMuscleGroup = MuscleGroup.Chest,      SecondaryMuscleGroups = [MuscleGroup.Triceps, MuscleGroup.Shoulders, MuscleGroup.Abs],                                                                          ImageUrl = "/exercises-image/chest/pushup.png" },

        // ── BACK ───────────────────────────────────────────────────────────────
        new() { Name = "Deadlift",                 Description = "Conventional barbell deadlift",               PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Hamstrings, MuscleGroup.Quads, MuscleGroup.Abs], IsCompetitionLift = true, CompetitionLiftType = CompetitionLiftType.Deadlift, ImageUrl = "/exercises-image/back/deadlift.png" },
        new() { Name = "Pull-Up",                  Description = "Bodyweight pull-up (pronated grip)",          PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Forearms],                                                                                             ImageUrl = "/exercises-image/back/pullup.png" },
        new() { Name = "Chin-Up",                  Description = "Bodyweight chin-up (supinated grip)",         PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps],                                                                                                                    ImageUrl = "/exercises-image/back/chinup.png" },
        new() { Name = "Barbell Row",              Description = "Bent-over barbell row",                       PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Forearms, MuscleGroup.Abs],                                                                            ImageUrl = "/exercises-image/back/barbellrow.png" },
        new() { Name = "Pendlay Row",              Description = "Strict barbell row from floor",               PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Abs],                                                                                                   ImageUrl = "/exercises-image/back/pendlayrow.png" },
        new() { Name = "Single-Arm Dumbbell Row",  Description = "One-arm dumbbell row on bench",               PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Forearms],                                                                                             ImageUrl = "/exercises-image/back/single-armdumbbellrow.png" },
        new() { Name = "Lat Pulldown",             Description = "Cable lat pulldown",                          PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Forearms],                                                                                             ImageUrl = "/exercises-image/back/latpulldown.png" },
        new() { Name = "Seated Cable Row",         Description = "Seated cable row machine",                    PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Forearms],                                                                                             ImageUrl = "/exercises-image/back/seadtedcablerow.png" },
        new() { Name = "T-Bar Row",                Description = "T-bar rowing machine",                        PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Abs],                                                                                                   ImageUrl = "/exercises-image/back/t-barrow.png" },
        new() { Name = "Face Pull",                Description = "Cable face pull for rear delts and back",     PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Shoulders],                                                                                                                 ImageUrl = "/exercises-image/back/facepull.png" },
        new() { Name = "Rack Pull",                Description = "Partial deadlift from knee height",           PrimaryMuscleGroup = MuscleGroup.Back,       SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Hamstrings],                                                                                            ImageUrl = "/exercises-image/back/rackpull.png" },

        // ── SHOULDERS ──────────────────────────────────────────────────────────
        new() { Name = "Overhead Press",           Description = "Barbell overhead shoulder press",             PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [MuscleGroup.Triceps, MuscleGroup.Abs],                                                                                                  ImageUrl = "/exercises-image/shoulder/overheadpress.png" },
        new() { Name = "Dumbbell Shoulder Press",  Description = "Seated or standing dumbbell press",           PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [MuscleGroup.Triceps],                                                                                                                   ImageUrl = "/exercises-image/shoulder/dumbbellshoulderpress.png" },
        new() { Name = "Arnold Press",             Description = "Arnold dumbbell shoulder press",              PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [MuscleGroup.Triceps],                                                                                                                   ImageUrl = "/exercises-image/shoulder/arnoldpress.png" },
        new() { Name = "Dumbbell Lateral Raise",   Description = "Dumbbell lateral raise",                      PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/shoulder/dumbbelllateralraise.png" },
        new() { Name = "Cable Lateral Raise",      Description = "Single-arm cable lateral raise",              PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/shoulder/cablelateralraise.png" },
        new() { Name = "Front Raise",              Description = "Dumbbell front raise",                        PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [MuscleGroup.Chest],                                                                                                                     ImageUrl = "/exercises-image/shoulder/frontraise.png" },
        new() { Name = "Reverse Fly",              Description = "Rear delt dumbbell fly",                      PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [MuscleGroup.Back],                                                                                                                      ImageUrl = "/exercises-image/shoulder/reversefly.png" },
        new() { Name = "Upright Row",              Description = "Barbell or cable upright row",                PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [MuscleGroup.Biceps, MuscleGroup.Forearms],                                                                                             ImageUrl = "/exercises-image/shoulder/uprightrow.png" },
        new() { Name = "Machine Shoulder Press",   Description = "Plate-loaded or selectorized shoulder press", PrimaryMuscleGroup = MuscleGroup.Shoulders,  SecondaryMuscleGroups = [MuscleGroup.Triceps],                                                                                                                   ImageUrl = "/exercises-image/shoulder/machineshoulderpress.png" },

        // ── BICEPS ─────────────────────────────────────────────────────────────
        new() { Name = "Barbell Curl",             Description = "Standing barbell bicep curl",                 PrimaryMuscleGroup = MuscleGroup.Biceps,     SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/biceps/barbellcurl.png" },
        new() { Name = "Dumbbell Curl",            Description = "Alternating dumbbell curl",                   PrimaryMuscleGroup = MuscleGroup.Biceps,     SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/biceps/dumbbellcurl.png" },
        new() { Name = "Hammer Curl",              Description = "Neutral grip dumbbell curl",                  PrimaryMuscleGroup = MuscleGroup.Biceps,     SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/biceps/hammercurl.png" },
        new() { Name = "Preacher Curl",            Description = "EZ-bar preacher curl",                        PrimaryMuscleGroup = MuscleGroup.Biceps,     SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/biceps/preachercurl.png" },
        new() { Name = "Cable Curl",               Description = "Low-cable bicep curl",                        PrimaryMuscleGroup = MuscleGroup.Biceps,     SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/biceps/cablecurl.png" },
        new() { Name = "Concentration Curl",       Description = "Single-arm concentration curl",               PrimaryMuscleGroup = MuscleGroup.Biceps,     SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/biceps/cocentrationcurl.png" },
        new() { Name = "Incline Dumbbell Curl",    Description = "Incline bench dumbbell curl for peak",        PrimaryMuscleGroup = MuscleGroup.Biceps,     SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/biceps/inclinedumbbellcurl.png" },

        // ── TRICEPS ────────────────────────────────────────────────────────────
        new() { Name = "Tricep Pushdown",          Description = "Cable tricep pushdown",                       PrimaryMuscleGroup = MuscleGroup.Triceps,    SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/triceps/triceppushdown.png" },
        new() { Name = "Skull Crusher",            Description = "EZ-bar lying tricep extension",               PrimaryMuscleGroup = MuscleGroup.Triceps,    SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/triceps/skillcrusher.png" },
        new() { Name = "Overhead Tricep Extension",Description = "Dumbbell or cable overhead tricep ext",       PrimaryMuscleGroup = MuscleGroup.Triceps,    SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/triceps/overheadtricepextension.png" },
        new() { Name = "Tricep Dip",               Description = "Parallel bar dips (upright torso)",           PrimaryMuscleGroup = MuscleGroup.Triceps,    SecondaryMuscleGroups = [MuscleGroup.Chest, MuscleGroup.Shoulders],                                                                                             ImageUrl = "/exercises-image/triceps/tricepdip.png" },
        new() { Name = "Close-Grip Bench Press",   Description = "Narrow grip barbell bench press",             PrimaryMuscleGroup = MuscleGroup.Triceps,    SecondaryMuscleGroups = [MuscleGroup.Chest, MuscleGroup.Shoulders],                                                                                             ImageUrl = "/exercises-image/triceps/close-gripbenchpress.png" },
        new() { Name = "Tricep Kickback",          Description = "Dumbbell tricep kickback",                    PrimaryMuscleGroup = MuscleGroup.Triceps,    SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/triceps/tricepkickback.png" },
        new() { Name = "Diamond Push-Up",          Description = "Close-grip push-up targeting triceps",        PrimaryMuscleGroup = MuscleGroup.Triceps,    SecondaryMuscleGroups = [MuscleGroup.Chest],                                                                                                                     ImageUrl = "/exercises-image/triceps/diamondpushup.png" },

        // ── QUADS ──────────────────────────────────────────────────────────────
        new() { Name = "Squat",                    Description = "Barbell back squat",                          PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Hamstrings, MuscleGroup.Abs], IsCompetitionLift = true, CompetitionLiftType = CompetitionLiftType.Squat, ImageUrl = "/exercises-image/quads/squat.png" },
        new() { Name = "Front Squat",              Description = "Barbell front squat",                         PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Abs],                                                                                                   ImageUrl = "/exercises-image/quads/frontsquat.png" },
        new() { Name = "Hack Squat",               Description = "Machine hack squat",                          PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes],                                                                                                                    ImageUrl = "/exercises-image/quads/hacksquat.png" },
        new() { Name = "Leg Press",                Description = "Machine leg press",                           PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Hamstrings],                                                                                            ImageUrl = "/exercises-image/quads/legpress.png" },
        new() { Name = "Leg Extension",            Description = "Machine leg extension",                       PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/quads/legextension.png" },
        new() { Name = "Lunge",                    Description = "Barbell or dumbbell lunge",                   PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Hamstrings, MuscleGroup.Calves],                                                                       ImageUrl = "/exercises-image/quads/lunge.png" },
        new() { Name = "Bulgarian Split Squat",    Description = "Rear-foot-elevated split squat",              PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Hamstrings],                                                                                            ImageUrl = "/exercises-image/quads/bulgariansplitsquat.png" },
        new() { Name = "Goblet Squat",             Description = "Dumbbell or kettlebell goblet squat",         PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Abs],                                                                                                   ImageUrl = "/exercises-image/quads/gobletsquat.png" },
        new() { Name = "Step-Up",                  Description = "Dumbbell step-up onto box",                   PrimaryMuscleGroup = MuscleGroup.Quads,      SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Calves],                                                                                                ImageUrl = "/exercises-image/quads/step-up.png" },

        // ── HAMSTRINGS ─────────────────────────────────────────────────────────
        new() { Name = "Romanian Deadlift",        Description = "RDL with barbell",                            PrimaryMuscleGroup = MuscleGroup.Hamstrings, SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Back],                                                                                                  ImageUrl = "/exercises-image/hamstring/romaniandeadlift.png" },
        new() { Name = "Sumo Deadlift",            Description = "Wide-stance sumo deadlift",                   PrimaryMuscleGroup = MuscleGroup.Hamstrings, SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Back, MuscleGroup.Quads],                                                                              ImageUrl = "/exercises-image/hamstring/sumodeadlift.png" },
        new() { Name = "Leg Curl",                 Description = "Machine lying or seated leg curl",             PrimaryMuscleGroup = MuscleGroup.Hamstrings, SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/hamstring/legcurl.png" },
        new() { Name = "Nordic Curl",              Description = "Partner-assisted nordic hamstring curl",       PrimaryMuscleGroup = MuscleGroup.Hamstrings, SecondaryMuscleGroups = [MuscleGroup.Glutes],                                                                                                                    ImageUrl = "/exercises-image/hamstring/mordiccurl.png" },
        new() { Name = "Good Morning",             Description = "Barbell good morning",                        PrimaryMuscleGroup = MuscleGroup.Hamstrings, SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Back],                                                                                                  ImageUrl = "/exercises-image/hamstring/goodmorning.png" },

        // ── GLUTES ─────────────────────────────────────────────────────────────
        new() { Name = "Hip Thrust",               Description = "Barbell hip thrust",                          PrimaryMuscleGroup = MuscleGroup.Glutes,     SecondaryMuscleGroups = [MuscleGroup.Hamstrings, MuscleGroup.Abs],                                                                                               ImageUrl = "/exercises-image/glutes/hipthurst.png" },
        new() { Name = "Glute Bridge",             Description = "Bodyweight or barbell glute bridge",          PrimaryMuscleGroup = MuscleGroup.Glutes,     SecondaryMuscleGroups = [MuscleGroup.Hamstrings, MuscleGroup.Abs],                                                                                               ImageUrl = "/exercises-image/glutes/glutebridge.png" },
        new() { Name = "Cable Kickback",           Description = "Cable glute kickback",                        PrimaryMuscleGroup = MuscleGroup.Glutes,     SecondaryMuscleGroups = [MuscleGroup.Hamstrings],                                                                                                                ImageUrl = "/exercises-image/glutes/cablekickback.png" },
        new() { Name = "Donkey Kick",              Description = "Bodyweight or cable donkey kick",             PrimaryMuscleGroup = MuscleGroup.Glutes,     SecondaryMuscleGroups = [MuscleGroup.Hamstrings],                                                                                                                ImageUrl = "/exercises-image/glutes/donkeykick.png" },
        new() { Name = "Sumo Squat",               Description = "Wide-stance bodyweight or goblet squat",      PrimaryMuscleGroup = MuscleGroup.Glutes,     SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Hamstrings],                                                                                             ImageUrl = "/exercises-image/glutes/sumodumbbellsquat.png" },

        // ── CALVES ─────────────────────────────────────────────────────────────
        new() { Name = "Standing Calf Raise",      Description = "Machine or barbell standing calf raise",      PrimaryMuscleGroup = MuscleGroup.Calves,     SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/calves/standingcalfraise.png" },
        new() { Name = "Seated Calf Raise",        Description = "Machine seated calf raise",                   PrimaryMuscleGroup = MuscleGroup.Calves,     SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/calves/seatedcalfraise.png" },
        new() { Name = "Donkey Calf Raise",        Description = "Donkey calf raise on machine or with belt",   PrimaryMuscleGroup = MuscleGroup.Calves,     SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/calves/donkeycalfraise.png" },
        new() { Name = "Single-Leg Calf Raise",    Description = "Bodyweight single-leg calf raise",            PrimaryMuscleGroup = MuscleGroup.Calves,     SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/calves/single-legcalfraise.png" },

        // ── ABS ────────────────────────────────────────────────────────────────
        new() { Name = "Plank",                    Description = "Forearm plank hold",                          PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [MuscleGroup.Shoulders],                                                                                                                 ImageUrl = "/exercises-image/abs/plank.png" },
        new() { Name = "Side Plank",               Description = "Lateral forearm plank hold",                  PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [MuscleGroup.Shoulders],                                                                                                                 ImageUrl = "/exercises-image/abs/sideplank.png" },
        new() { Name = "Crunch",                   Description = "Bodyweight abdominal crunch",                 PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/abs/crunch.png" },
        new() { Name = "Decline Crunch",           Description = "Crunch on a decline bench",                   PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/abs/declinecrunch.png" },
        new() { Name = "Hanging Leg Raise",        Description = "Hanging bar leg raise",                       PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/abs/hanginlegraise.png" },
        new() { Name = "Cable Crunch",             Description = "Kneeling cable crunch",                       PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/abs/cablecrunch.png" },
        new() { Name = "Ab Wheel Rollout",         Description = "Ab wheel roll-out",                           PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [MuscleGroup.Shoulders, MuscleGroup.Back],                                                                                               ImageUrl = "/exercises-image/abs/abwheelrollout.png" },
        new() { Name = "Russian Twist",            Description = "Seated rotational core exercise",             PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/abs/russiantwist.png" },
        new() { Name = "Pallof Press",             Description = "Anti-rotation cable Pallof press",            PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [MuscleGroup.Shoulders],                                                                                                                 ImageUrl = "/exercises-image/abs/pallofpress.png" },
        new() { Name = "Dragon Flag",              Description = "Bruce Lee dragon flag",                       PrimaryMuscleGroup = MuscleGroup.Abs,        SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/abs/dragonflag.png" },

        // ── FOREARMS ───────────────────────────────────────────────────────────
        new() { Name = "Wrist Curl",               Description = "Barbell wrist curl",                          PrimaryMuscleGroup = MuscleGroup.Forearms,   SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/forearms/wristcurl.png" },
        new() { Name = "Reverse Wrist Curl",       Description = "Barbell reverse wrist curl",                  PrimaryMuscleGroup = MuscleGroup.Forearms,   SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/forearms/reversewristcurl.png" },
        new() { Name = "Farmer's Walk",            Description = "Heavy dumbbell carry",                        PrimaryMuscleGroup = MuscleGroup.Forearms,   SecondaryMuscleGroups = [MuscleGroup.Abs, MuscleGroup.Shoulders],                                                                                               ImageUrl = "/exercises-image/forearms/farmerwalk.png" },
        new() { Name = "Plate Pinch",              Description = "Plate pinch hold for grip strength",          PrimaryMuscleGroup = MuscleGroup.Forearms,   SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/forearms/platepinch.png" },

        // ── TRAPS ──────────────────────────────────────────────────────────────
        new() { Name = "Barbell Shrug",            Description = "Standing barbell shrug",                      PrimaryMuscleGroup = MuscleGroup.Traps,      SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/traps/barbellshrug.png" },
        new() { Name = "Dumbbell Shrug",           Description = "Standing dumbbell shrug",                     PrimaryMuscleGroup = MuscleGroup.Traps,      SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/traps/dumbbelshrug.png" },
        new() { Name = "Smith Machine Shrug",      Description = "Smith machine trap shrug",                    PrimaryMuscleGroup = MuscleGroup.Traps,      SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/traps/smithmachineshrug.png" },
        new() { Name = "Trap Bar Shrug",           Description = "Trap bar shrug",                              PrimaryMuscleGroup = MuscleGroup.Traps,      SecondaryMuscleGroups = [MuscleGroup.Forearms],                                                                                                                  ImageUrl = "/exercises-image/traps/trapbarshrug.png" },
        new() { Name = "High Pull",                Description = "Barbell high pull",                           PrimaryMuscleGroup = MuscleGroup.Traps,      SecondaryMuscleGroups = [MuscleGroup.Shoulders, MuscleGroup.Back],                                                                                               ImageUrl = "/exercises-image/traps/highpull.png" },

        // ── ADDUCTORS ──────────────────────────────────────────────────────────
        new() { Name = "Hip Adduction Machine",    Description = "Seated machine hip adduction",               PrimaryMuscleGroup = MuscleGroup.Adductors,  SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/adductors/hipadductionmachine.png" },
        new() { Name = "Copenhagen Plank",         Description = "Side plank variation for adductors",          PrimaryMuscleGroup = MuscleGroup.Adductors,  SecondaryMuscleGroups = [MuscleGroup.Abs],                                                                                                                       ImageUrl = "/exercises-image/adductors/copenhagenplank.png" },
        new() { Name = "Cable Hip Adduction",      Description = "Standing cable hip adduction",                PrimaryMuscleGroup = MuscleGroup.Adductors,  SecondaryMuscleGroups = [],                                                                                                                                      ImageUrl = "/exercises-image/adductors/cablehipadduction.png" },
        new() { Name = "Sumo Leg Press",           Description = "Wide-stance leg press",                       PrimaryMuscleGroup = MuscleGroup.Adductors,  SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Glutes],                                                                                                ImageUrl = "/exercises-image/adductors/sumolegpress.png" },
        new() { Name = "Side Lunge",               Description = "Lateral lunge",                               PrimaryMuscleGroup = MuscleGroup.Adductors,  SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Glutes],                                                                                                ImageUrl = "/exercises-image/adductors/sidelunge.png" },

        // ── ABDUCTORS ──────────────────────────────────────────────────────────
        new() { Name = "Hip Abduction Machine",    Description = "Seated machine hip abduction",               PrimaryMuscleGroup = MuscleGroup.Abductors,  SecondaryMuscleGroups = [MuscleGroup.Glutes],                                                                                                                    ImageUrl = "/exercises-image/abductors/hipabductionmachine.png" },
        new() { Name = "Cable Hip Abduction",      Description = "Standing cable hip abduction",                PrimaryMuscleGroup = MuscleGroup.Abductors,  SecondaryMuscleGroups = [MuscleGroup.Glutes],                                                                                                                    ImageUrl = "/exercises-image/abductors/cablehipabduction.png" },
        new() { Name = "Banded Lateral Walk",      Description = "Mini-band lateral walk",                      PrimaryMuscleGroup = MuscleGroup.Abductors,  SecondaryMuscleGroups = [MuscleGroup.Glutes],                                                                                                                    ImageUrl = "/exercises-image/abductors/bandedlateralwalk.png" },
        new() { Name = "Clamshell",                Description = "Side-lying clamshell",                        PrimaryMuscleGroup = MuscleGroup.Abductors,  SecondaryMuscleGroups = [MuscleGroup.Glutes],                                                                                                                    ImageUrl = "/exercises-image/abductors/clamshell.png" },
        new() { Name = "Side-Lying Leg Raise",     Description = "Side-lying hip abduction raise",              PrimaryMuscleGroup = MuscleGroup.Abductors,  SecondaryMuscleGroups = [MuscleGroup.Glutes],                                                                                                                    ImageUrl = "/exercises-image/abductors/side-lyinglegraise.png" },

        // ── FULL BODY ──────────────────────────────────────────────────────────
        new() { Name = "Burpee",                   Description = "Full body burpee",                            PrimaryMuscleGroup = MuscleGroup.FullBody,   SecondaryMuscleGroups = [MuscleGroup.Chest, MuscleGroup.Abs, MuscleGroup.Quads],                                                                                ImageUrl = "/exercises-image/fullbody/burpee.png" },
        new() { Name = "Clean and Press",          Description = "Barbell power clean and press",               PrimaryMuscleGroup = MuscleGroup.FullBody,   SecondaryMuscleGroups = [MuscleGroup.Shoulders, MuscleGroup.Back, MuscleGroup.Quads],                                                                           ImageUrl = "/exercises-image/fullbody/cleanandpress.png" },
        new() { Name = "Kettlebell Swing",         Description = "Two-hand kettlebell swing",                   PrimaryMuscleGroup = MuscleGroup.FullBody,   SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Hamstrings, MuscleGroup.Abs],                                                                          ImageUrl = "/exercises-image/fullbody/kettlebellswing.png" },
        new() { Name = "Thruster",                 Description = "Front squat to overhead press",               PrimaryMuscleGroup = MuscleGroup.FullBody,   SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Shoulders, MuscleGroup.Abs],                                                                            ImageUrl = "/exercises-image/fullbody/thruster.png" },
        new() { Name = "Turkish Get-Up",           Description = "Kettlebell Turkish get-up",                   PrimaryMuscleGroup = MuscleGroup.FullBody,   SecondaryMuscleGroups = [MuscleGroup.Shoulders, MuscleGroup.Abs, MuscleGroup.Glutes],                                                                           ImageUrl = "/exercises-image/fullbody/turkishget-up.png" },
        new() { Name = "Box Jump",                 Description = "Plyometric jump onto a box",                  PrimaryMuscleGroup = MuscleGroup.FullBody,   SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Glutes, MuscleGroup.Calves],                                                                            ImageUrl = "/exercises-image/fullbody/boxjump.png" },

        // ── CARDIO ─────────────────────────────────────────────────────────────
        new() { Name = "Running",                  Description = "Treadmill or outdoor running",                 PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Calves, MuscleGroup.Glutes],     ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 9.8m,  ImageUrl = "/exercises-image/cardio/running.png" },
        new() { Name = "Cycling",                  Description = "Stationary bike or outdoor cycling",          PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Glutes, MuscleGroup.Calves],     ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 7.5m,  ImageUrl = "/exercises-image/cardio/cycling.png" },
        new() { Name = "Rowing Machine",           Description = "Ergometer rowing machine",                    PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Back, MuscleGroup.Shoulders, MuscleGroup.Quads],    ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 7.0m,  ImageUrl = "/exercises-image/cardio/rowlingmachine.png" },
        new() { Name = "Jump Rope",                Description = "Skipping rope cardio",                        PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Calves, MuscleGroup.Shoulders],                     ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 10.0m, ImageUrl = "/exercises-image/cardio/jumprope.png" },
        new() { Name = "Assault Bike",             Description = "Fan bike full-body cardio",                   PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Shoulders, MuscleGroup.Quads],                      ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 9.0m,  ImageUrl = "/exercises-image/cardio/assaultbike.png" },
        new() { Name = "Elliptical",               Description = "Elliptical cross-trainer",                    PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Glutes],                         ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 5.5m,  ImageUrl = "/exercises-image/cardio/elliptical.png" },
        new() { Name = "Stair Climber",            Description = "Stair climber machine",                       PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Glutes, MuscleGroup.Quads, MuscleGroup.Calves],     ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 8.8m,  ImageUrl = "/exercises-image/cardio/stairclimber.png" },
        new() { Name = "Mountain Climber",         Description = "Bodyweight mountain climber",                 PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Abs, MuscleGroup.Shoulders],                        ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 8.0m,  ImageUrl = "/exercises-image/cardio/mountainclimber.png" },
        new() { Name = "Treadmill Walk",           Description = "Steady-pace walking on treadmill",            PrimaryMuscleGroup = MuscleGroup.Cardio,     SecondaryMuscleGroups = [MuscleGroup.Quads, MuscleGroup.Calves, MuscleGroup.Glutes],     ExerciseKind = ExerciseKind.Cardio, EstimatedMet = 3.5m,  ImageUrl = "/exercises-image/cardio/treadmillwalk.png" },
    ];
}
