using Mediator;
using Xenoh.Application.Common.Interfaces;
using Xenoh.Application.Common.Interfaces.Repositories;
using Xenoh.Domain.Entities;
using Xenoh.Domain.Enums;

namespace Xenoh.Application.Features.Subscriptions.Commands.CreatePaymentOrder;

public sealed class CreatePaymentOrderHandler(
    ISubscriptionRepository subscriptionRepo,
    IPaymentOrderRepository paymentOrderRepo,
    ICurrentUserService currentUser,
    ISePayBankInfo bankInfo
) : IRequestHandler<CreatePaymentOrderCommand, PaymentOrderResponse>
{
    public async ValueTask<PaymentOrderResponse> Handle(
        CreatePaymentOrderCommand request, CancellationToken cancellationToken)
    {
        if (request.RequestedTier == PlanTier.Free)
            throw new InvalidOperationException("Cannot create a payment order for the Free tier.");

        decimal amount;
        try { amount = SubscriptionLimits.GetPrice(request.RequestedTier, request.DurationMonths); }
        catch { throw new InvalidOperationException("Invalid tier/duration combination."); }

        ValidateBankInfo();

        var userId = currentUser.UserId;

        // Expire any existing pending order for the same tier
        var existing = await paymentOrderRepo.FindPendingByUserAndTierAsync(
            userId, request.RequestedTier, cancellationToken);
        if (existing is not null)
        {
            existing.Status = PaymentStatus.Expired;
            existing.UpdatedAt = DateTime.UtcNow;
        }

        var subscription = await subscriptionRepo.FindByUserIdAsync(userId, cancellationToken);
        if (subscription is null)
        {
            subscription = new UserSubscription { UserId = userId, Tier = PlanTier.Free };
            await subscriptionRepo.AddAsync(subscription, cancellationToken);
            await subscriptionRepo.SaveChangesAsync(cancellationToken);
        }

        // Build order — Id is auto-generated by BaseEntity initializer
        var order = new PaymentOrder
        {
            UserId = userId,
            SubscriptionId = subscription.Id,
            RequestedTier = request.RequestedTier,
            Amount = amount,
            DurationMonths = request.DurationMonths,
            Status = PaymentStatus.Pending,
            ExpiresAt = DateTime.UtcNow.AddHours(24)
        };

        // Derive transfer code from auto-generated Id (available before SaveChanges)
        // No special chars — MBBank and most Vietnamese banks only allow alphanumeric + spaces
        var transferCode = $"XENOH{userId.ToString("N")[..8].ToUpper()}{order.Id.ToString("N")[..8].ToUpper()}";
        order.TransferCode = transferCode;

        await paymentOrderRepo.AddAsync(order, cancellationToken);
        await paymentOrderRepo.SaveChangesAsync(cancellationToken);

        return new PaymentOrderResponse(
            order.Id,
            transferCode,
            amount,
            request.DurationMonths,
            request.RequestedTier.ToString(),
            order.ExpiresAt,
            bankInfo.BankAccountNumber,
            bankInfo.BankAccountName,
            bankInfo.BankName,
            transferCode);
    }

    private void ValidateBankInfo()
    {
        if (IsMissing(bankInfo.BankAccountNumber) ||
            IsMissing(bankInfo.BankAccountName) ||
            IsMissing(bankInfo.BankName))
        {
            throw new InvalidOperationException("SePay bank information is not configured.");
        }
    }

    private static bool IsMissing(string value) =>
        string.IsNullOrWhiteSpace(value) ||
        value.StartsWith("YOUR_", StringComparison.OrdinalIgnoreCase);
}
