using Mediator;
using Microsoft.EntityFrameworkCore;
using Xenoh.Application.Common.Exceptions;
using Xenoh.Application.Common.Interfaces;
using Xenoh.Application.Common.Interfaces.Repositories;
using Xenoh.Application.Features.Promotions;
using Xenoh.Domain.Entities;
using Xenoh.Domain.Enums;

namespace Xenoh.Application.Features.Subscriptions.Commands.CreatePaymentOrder;

public sealed class CreatePaymentOrderHandler(
    ISubscriptionRepository subscriptionRepo,
    IPaymentOrderRepository paymentOrderRepo,
    IApplicationDbContext db,
    ICurrentUserService currentUser,
    ISePayBankInfo bankInfo,
    IPaymentPreflightService preflight,
    ISubscriptionActivationService subscriptionActivation
) : IRequestHandler<CreatePaymentOrderCommand, PaymentOrderResponse>
{
    public async ValueTask<PaymentOrderResponse> Handle(
        CreatePaymentOrderCommand request, CancellationToken cancellationToken)
    {
        SubscriptionContract.EnsureCurrentTermsAccepted(request.AcceptedTerms, request.TermsVersion);

        if (request.RequestedTier == PlanTier.Free)
            throw new InvalidOperationException("Cannot create a payment order for the Free tier.");
        if (request.RequestedTier == PlanTier.Organizer)
            throw new InvalidOperationException("Organizer plans are activated by an administrator after contacting Xenoh support.");

        var offer = SubscriptionCatalog.GetRequired(request.RequestedTier, request.DurationMonths);
        var amount = offer.Price;

        var userId = currentUser.UserId;

        // Resolve promotion code (validated with the same rules as the preview endpoint)
        var originalAmount = amount;
        var discountAmount = 0m;
        PromotionCode? promo = null;
        if (!string.IsNullOrWhiteSpace(request.PromotionCode))
        {
            var code = PromotionEvaluation.NormalizeCode(request.PromotionCode);
            promo = await db.PromotionCodes
                .FirstOrDefaultAsync(p => p.Code == code, cancellationToken)
                ?? throw new InvalidOperationException("Invalid promotion code.");
        }

        if (promo is not null)
        {
            var promoError = await PromotionEvaluation.CheckEligibilityAsync(
                db, promo, userId, request.RequestedTier, cancellationToken);
            if (promoError is not null)
                throw new InvalidOperationException(promoError);

            discountAmount = PromotionEvaluation.ComputeDiscount(promo, amount);
            amount -= discountAmount;
        }

        var paymentRequired = amount > 0m;
        if (paymentRequired)
        {
            ValidateBankInfo();

            // Fail closed before showing payment instructions: if SePay is unreachable or the
            // server can't honor a payment, don't let the user transfer money we couldn't refund.
            var health = await preflight.CheckAsync(cancellationToken);
            if (!health.Healthy)
                throw new PaymentServiceUnavailableException(
                    health.Reason ?? "Payment service is temporarily unavailable. Please try again later.");
        }

        // Expire any existing pending order for the same tier
        var existing = await paymentOrderRepo.FindPendingByUserAndTierAsync(
            userId, request.RequestedTier, cancellationToken);
        if (existing is not null)
        {
            existing.Status = PaymentStatus.Expired;
            existing.UpdatedAt = DateTime.UtcNow;
        }

        UserSubscription? subscription = null;
        if (paymentRequired)
        {
            subscription = await subscriptionRepo.FindByUserIdAsync(userId, cancellationToken);
            if (subscription is null)
            {
                subscription = new UserSubscription { UserId = userId, Tier = PlanTier.Free };
                await subscriptionRepo.AddAsync(subscription, cancellationToken);
                await subscriptionRepo.SaveChangesAsync(cancellationToken);
            }
        }

        // Build order — Id is auto-generated by BaseEntity initializer
        var now = DateTime.UtcNow;
        var order = new PaymentOrder
        {
            UserId = userId,
            SubscriptionId = subscription?.Id ?? Guid.Empty,
            RequestedTier = request.RequestedTier,
            Amount = amount,
            DiscountAmount = discountAmount,
            PromotionCodeId = promo?.Id,
            DurationMonths = request.DurationMonths,
            Status = paymentRequired ? PaymentStatus.Pending : PaymentStatus.Completed,
            PaidAt = paymentRequired ? null : now,
            ExpiresAt = now.AddHours(24)
        };

        // Derive transfer code from auto-generated Id (available before SaveChanges)
        // No special chars — MBBank and most Vietnamese banks only allow alphanumeric + spaces
        var transferCode = $"XENOH{userId.ToString("N")[..8].ToUpper()}{order.Id.ToString("N")[..8].ToUpper()}";
        order.TransferCode = transferCode;

        var legalAcceptance = new LegalAcceptance
        {
            UserId = userId,
            DocumentType = LegalDocumentType.TermsOfService,
            DocumentVersion = SubscriptionContract.CurrentTermsVersion,
            AcceptedAt = DateTime.UtcNow,
            PaymentOrderId = order.Id
        };

        if (paymentRequired)
        {
            db.LegalAcceptances.Add(legalAcceptance);
            await paymentOrderRepo.AddAsync(order, cancellationToken);
            await paymentOrderRepo.SaveChangesAsync(cancellationToken);
        }
        else
        {
            await subscriptionActivation.ActivateComplimentaryAsync(order, legalAcceptance, cancellationToken);
        }

        return new PaymentOrderResponse(
            order.Id,
            transferCode,
            amount,
            originalAmount,
            discountAmount,
            promo?.Code,
            request.DurationMonths,
            request.RequestedTier.ToString(),
            order.ExpiresAt,
            bankInfo.BankAccountNumber,
            bankInfo.BankAccountName,
            bankInfo.BankName,
            transferCode,
            paymentRequired);
    }

    private void ValidateBankInfo()
    {
        if (IsMissing(bankInfo.BankAccountNumber) ||
            IsMissing(bankInfo.BankAccountName) ||
            IsMissing(bankInfo.BankName))
        {
            throw new InvalidOperationException("SePay bank information is not configured.");
        }
    }

    private static bool IsMissing(string value) =>
        string.IsNullOrWhiteSpace(value) ||
        value.StartsWith("YOUR_", StringComparison.OrdinalIgnoreCase);
}
